{"name": "test_to_fail", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5", "trace": "def test_to_fail():\n>   \tassert 4 == 5\nE    assert 4 == 5\n\ntest_users.py:95: AssertionError"}, "start": 1642347784589, "stop": 1642347784589, "uuid": "07086398-49ac-4169-b492-31ddcfcdb007", "historyId": "aff230572e5b01f063716943031e84ae", "testCaseId": "024e06c9d8dee8d4003bbbceab4d0952", "fullName": "test_users#test_to_fail", "labels": [{"name": "suite", "value": "test_users"}, {"name": "host", "value": "adminpc-Latitude-5591"}, {"name": "thread", "value": "2768-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_users"}]}